default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: sarva
  password: sarvapostgre
  pool: 5

development:
  <<: *default
  database: clinic_portal_development

test:
  <<: *default
  database: clinic_portal_test
